config/routes.rb
Rails.application.routes.draw do
  resources :availabilities, only: [:destroy]

  devise_for :admins
  devise_for :users
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  get 'my_account/view'
  get 'admin/input'
  get 'admin/view'
  get 'availabilities/index'
  post 'availabilities/destroy'
  get 'masters/available_times'
  get 'appointment1/index'
  get 'appointment1/view'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/contact'
  root 'static_pages#home'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :master
  validates :date, uniqueness: { scope: :master_id}

end

app/models/listing_ap.rb
class ListingAp < ApplicationRecord
  validates :date, uniqueness: true
end

app/models/master.rb
class Master < ApplicationRecord
  has_many :availabilities

  validates :name, uniqueness: true
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def input
    @master = User.all


    @zap = ListingAp.all
  end

  def view
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/appointment1_controller.rb
class Appointment1Controller < ApplicationController
  def index
    # Делаем что-то с полученными значениями, например, создаем новую запись в базе данных
  end



  def view

    name = params[:name]
    phoneNumber = params[:phoneNumber]
    date1 = params[:date]
    master_name = params[:master_name]
    @result = "error"
    if (name!= "") && (phoneNumber != "") && (date1 != "") && (master_name != "")
      master = Master.find_by(name: master_name)
      id = master.id
      availabilities = Availability.find_by(date: date1, master_id: id)
      availabilities.availible = 0

      if availabilities.changed?
        if availabilities.save
          @result = "Success"
         post=ListingAp.new(date: date1, email: phoneNumber, master_name: master_name)
         post.save
        else
          @result = "Fault"
        end
      else
        @result = "nothing changed"
      end
    else
      @result = "error"
    end



    render json: {response: @result}








  end
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  def available_times
    @name = Master.all.map{|a| a.name}
    render json: @name
  end
end

app/controllers/my_account_controller.rb
class MyAccountController < ApplicationController
  def view
    if current_user
    @email = current_user.email
    @history_zap = ListingAp.where(email: @email)
    end

  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment1_helper.rb
module Appointment1Helper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/my_account_helper.rb
module MyAccountHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/input.html.erb
<%if current_admin  %>
<h1>Users</h1>
<ul>
  <% @master.each do |user| %>
    <li><%= user.email %></li>
  <% end %>
</ul>


<h1>Appointments</h1>
<ul>
  <% @zap.each do |ap| %>
    <li><%= ap.date %></li>
    <p><%=ap.email %></p>
  <% end %>
</ul>
  <%else%>
  <p>Oops</p>
<%end %>

app/views/admin/view.html.erb
<h1>Admin#view</h1>
<p>Find me in app/views/admin/view.html.erb</p>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= t("navigation.home") %> </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/appointment1/index"><%= t("navigation.makeup")%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/static_pages/about"><%= t("navigation.about")%></a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to t("navigation.my_acc"), my_account_view_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to t("navigation.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <%elsif current_admin%>
          <li class="nav-item"> <%= button_to t("navigation.sign_out"), destroy_admin_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
          <li class="nav-item"> <%= link_to t("navigation.admin_panel"), admin_input_path, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to t("navigation.sign_up"), new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to t("navigation.sign_in"), new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
    <div><%= link_to "English ", url_for(locale: "en") %>
      <%= link_to "Русский", url_for(locale: "ru") %></div>



    <!--          <div class = "centered-div">-->
<!--            <h1 style="font-family: 'Roboto', sans-serif;"> Estethic </h1>-->
<!--          </div>-->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonBeta2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="container-fluid">
    <%= yield %>
  </div>
<!--  <div class="custom-heading">-->

<!--    <div class="btn-group">-->

<!--      <a href="<%#= root_path %>" class="btn btn-primary">главная</a>-->


<!--      <a href="<%#= static_pages_about_path %>" class="btn btn-secondary">О нас</a>-->


<!--      <a href="<%#= url_for(controller: 'appointment1', action: 'index') %>" class="btn btn-secondary">Записаться в салон</a>-->
<!--      <div class = "centered-div">-->
<!--        <h1 class="custom-heading"> Estethic </h1>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class = "centered-div">-->
<!--      <h1 class="custom-heading"> Estethic </h1>-->
<!--    </div>-->
<!--  </div>-->
  </body>
</html>